# Linear Regression 실습

이번 실습에서는 linear regression에 대한 gradient descent를 직접 구현해봅니다. 여기서 사용할 문제들은 크게 두 가지로 OR 문제와 XOR 문제입니다.

먼저 필요한 library들을 import합시다.

In [150]:
import torch
import numpy as np

In [151]:
from torch import Tensor
from typing import List, Tuple, Dict, Any, Union

## NOTE

텐서로 정의되는 2차원이 4개 들어가있는 x 한개를 (4,2) 라고 부른다?
아님 2차원 데이터 4개?를 표현한 것?

### randn 의 정의

randn 은 표준 정규 분포에서 랜덤 샘플을 추출하는 함수이다

In [152]:

# 1차원 텐서 생성 (길이 4)
x = torch.randn(4)
# 결과 예시: tensor([-2.1436, 0.9966, 2.3426, -0.6366])

# 2차원 텐서 생성 (2행 3열)
y = torch.randn(2, 3)
# 결과 예시: tensor([[ 1.5954, 2.8929, -1.0923],
#                   [ 1.1719, -0.4709, -0.1996]])

## OR Problem

OR은 0 또는 1의 값을 가질 수 있는 두 개의 정수를 입력으로 받아 둘 중에 하나라도 1이면 1을 출력하고 아니면 0을 출력하는 문제입니다.
즉, 우리가 학습하고자 하는 함수는 2개의 정수를 입력받아 하나의 정수를 출력하면됩니다. 이러한 함수를 학습하기 위한 data는 다음과 같이 구성할 수 있습니다.

## NOTE

텐서를 정의하는 개념에 대해 설명한다
우선 하나의 텐서에 대한 정의로 n차원이든 정의된다

그리고 그 크기에 대해 사이즈를 아래 예시의 2차원 백터 4 개는 [4,2] 처럼 정의된다
여기서 사람의 해석 방법과 텐서의 해석 방법이 다른데
텐서는 데이터의 개수를 먼저 정의하고 그 뒤에 데이터의 차원을 세고 있는 것을 알 수 있다

```
x = torch.tensor([
    [0., 0.],
    [0., 1.],
    [1., 0.],
    [1., 1.]
]) 
```
에 대해 해석할 때

해석하면 다음과 같다 일단 텐서에는 4개의 A 텐서가 있다 > A는 벡터를 담고 있는 텐서이다?
이러한 텐서의 정의를 통해 우리는 데이터의 개수와 데이터의 차원을 명확하게 알 수 있고 이를 통해 우리는 데이터의 형태를 파악할 수 있다

아래의 x와 y는 입력 데이터와 출력 데이터다

or이기 때문에 정답이 0,1,1,1 인 것

In [153]:
x = torch.tensor([
    [0., 0.],
    [0., 1.],
    [1., 0.],
    [1., 1.]
])
y = torch.tensor([0, 1, 1, 1])

print(x.shape, y.shape)


torch.Size([4, 2]) torch.Size([4])


출력 결과에서 볼 수 있다시피 $x$의 shape은 (4, 2)로, 총 4개의 two-dimensional data 임을 알 수 있습니다. $y$는 각 $x_i$에 대한 label로 우리가 설정한 문제의 조건을 잘 따라가는 것을 알 수 있습니다.

다음으로는 linear regression의 parameter들인 $w, b$를 정의하겠습니다.

In [174]:
w = torch.randn((1, 2))
b = torch.randn((1, 1))

print(w.shape, b.shape)
print(w, b)



torch.Size([1, 2]) torch.Size([1, 1])
tensor([[0.3566, 0.1005]]) tensor([[0.1993]])


$w$는 1x2의 벡터이고 $b$는 1x1의 scalar임을 알 수 있습니다. 여기서는 `torch.randn`을 사용하여 standard normal distribution을 가지고 초기화하였습니다.

이러한 $w, b$와 data $x, y$가 주어졌을 때 우리가 학습한 $w, b$의 성능을 평가하는 함수를 구현합시다.
평가 함수는 다음과 같이 MSE로 정의됩니다:
$$l(f) := MSE(f(x), y) = \frac{1}{n} \sum_{i=1}^n (f(x_i) - y)^2.$$
이를 구현한 코드는 다음과 같습니다.

## NOTE

여기서 w는 전체 영역의 크기에 대해 정의하고 있고
b는 한개의 스칼라를 정의하고 있음을 알 수 있다


pred 는 결과 출력할 때 사용한 함수임

w는 전체 영역의 현재 가중치
x.T 는 현재 
b는 현재 입력 값에 대한 편향

In [178]:
def pred(w, b, x):
  print('pred:',w, b, x ,x.T)
  return torch.matmul(w, x.T) + b


def loss(w, b, x, y):
  return (y - pred(w, b, x)).pow(2).mean()

먼저 `def pred(w, b, x)`는 $wx^T + b$, 즉 1차 함수 $f$의 $x$에 대한 결과를 반환하는 함수를 구현했습니다.
이를 이용하여 주어진 label $y$와의 MSE를 측정하는 코드가 `def loss(w, b, x, y)`에 구현되어있습니다.

다음은 MSE를 기반으로 $w, b$의 gradient를 구하는 코드를 구현하겠습니다.
MSE에 대한 $w$의 gradient는 다음과 같이 구할 수 있습니다:
$$\frac{\partial l}{\partial w} = \frac{1}{n} \sum_{i=1}^n 2(wx_i^T + b - y)x_i.$$
$b$에 대한 gradient는 다음과 같습니다:
$$\frac{\partial l}{\partial b} = \frac{1}{n} \sum_{i=1}^n 2(wx_i^T + b - y).$$
이를 코드로 구현하면 다음과 같습니다.

In [156]:
def grad_w(w, b, x, y):
  # w: (1, d), b: (1, 1), x: (n, d), y: (n)
  tmp1 = torch.matmul(w, x.T)  # (1, n)
  tmp2 = tmp1 + b              # (1, n)
  tmp3 = 2 * (tmp2 - y[None])  # (1, n)
  grad_item = tmp3.T * x       # (n, d)
  return grad_item.mean(dim=0, keepdim=True)  # (1, d)


def grad_b(w, b, x, y):
  # w: (1, d), b: (1, 1), x: (n, d), y: (n)
  grad_item = 2 * (torch.matmul(w, x.T) + b - y[None])  # (1, n)
  return grad_item.mean(dim=-1, keepdim=True)           # (1, 1)

여기서 중요한 것은 shape에 맞춰서 연산을 잘 사용해야한다는 것입니다. Shape과 관련된 설명은 `[Chapter 0]`의 Numpy에서 설명했으니, 복습하신다는 느낌으로 주석으로 써놓은 shape들을 유도해보시면 좋을 것 같습니다. 중요한 것은 반환되는 tensor의 shape이 우리가 구하고자 하는 gradient와 일치해야 한다는 것입니다. 예를 들어 $w$의 $l$에 대한 gradient는 $w$와 shape이 동일해야 합니다.

마지막으로 gradient descent 함수를 구현하겠습니다. Gradient descent는 다음과 같이 정의됩니다:
$$w^{(new)} = w^{(old)} - \eta \frac{\partial l}{\partial w} \biggr\rvert_{w = w^{(old)}}.$$
Gradient는 위에서 구현했으니 이를 활용하여 learning rate $\eta$가 주어졌을 때 $w, b$를 update하는 코드를 구현할 수 있습니다. 구현한 결과는 다음과 같습니다.

In [157]:
def update(x, y, w, b, lr):
  w = w - lr * grad_w(w, b, x, y)
  b = b - lr * grad_b(w, b, x, y)
  return w, b

Gradient descent에 해당하는 코드는 모두 구현하였습니다. 이제 학습하는 코드를 구현하겠습니다:

In [158]:
def train(n_epochs, lr, w, b, x, y):
  for e in range(n_epochs):
    w, b = update(x, y, w, b, lr)
    print(f"Epoch {e:3d} | Loss: {loss(w, b, x, y)}")
  return w, b

여기서 `n_epochs`는 update를 하는 횟수를 의미합니다. 매 update 이후에 `loss` 함수를 사용하여 잘 수렴하고 있는지 살펴봅니다. 실제로 이 함수를 실행한 결과는 다음과 같습니다.

In [171]:
n_epochs = 100
lr = 0.1

w, b = train(n_epochs, lr, w, b, x, y)
print(w, b)

Epoch   0 | Loss: 0.0624999962747097
Epoch   1 | Loss: 0.0624999962747097
Epoch   2 | Loss: 0.0624999962747097
Epoch   3 | Loss: 0.0624999962747097
Epoch   4 | Loss: 0.0624999962747097
Epoch   5 | Loss: 0.0624999962747097
Epoch   6 | Loss: 0.0624999962747097
Epoch   7 | Loss: 0.0624999962747097
Epoch   8 | Loss: 0.0624999962747097
Epoch   9 | Loss: 0.0624999962747097
Epoch  10 | Loss: 0.0624999962747097
Epoch  11 | Loss: 0.0624999962747097
Epoch  12 | Loss: 0.0624999962747097
Epoch  13 | Loss: 0.0624999962747097
Epoch  14 | Loss: 0.0624999962747097
Epoch  15 | Loss: 0.0624999962747097
Epoch  16 | Loss: 0.0624999962747097
Epoch  17 | Loss: 0.0624999962747097
Epoch  18 | Loss: 0.0624999962747097
Epoch  19 | Loss: 0.0624999962747097
Epoch  20 | Loss: 0.0624999962747097
Epoch  21 | Loss: 0.0624999962747097
Epoch  22 | Loss: 0.0624999962747097
Epoch  23 | Loss: 0.0624999962747097
Epoch  24 | Loss: 0.0624999962747097
Epoch  25 | Loss: 0.0624999962747097
Epoch  26 | Loss: 0.0624999962747097
E

잘 수렴하는 것을 확인하였습니다. 마지막으로 OR data에 대한 $w, b$의 예측 결과와 label을 비교해봅시다.

In [180]:
print(pred(w, b, x))
print(y)

pred: tensor([[0.3566, 0.1005]]) tensor([[0.1993]]) tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]]) tensor([[0., 0., 1., 1.],
        [0., 1., 0., 1.]])
tensor([[0.1993, 0.2998, 0.5559, 0.6564]])
tensor([0, 1, 1, 1])


아래 값으로 수렴하는 것을 볼 수 있음

tensor([[0.2500, 0.7500, 0.7500, 1.2500]])
tensor([0, 1, 1, 1])

예측 결과를 볼 수 있다시피 우리의 linear regression model은 0과 1에 해당하는 data를 잘 구분하는 것을 알 수 있습니다.

# XOR Problem

이번에는 XOR를 학습해보겠습니다. XOR은 OR과 똑같은 입력을 받는 문제로, 두 개의 0 또는 1의 정수가 들어왔을 때 두 정수가 다르면 1, 아니면 0을 출력해야 합니다.
먼저 data를 만들어보겠습니다:

In [161]:
# x = torch.tensor([
#     [0., 0.],
#     [0., 1.],
#     [1., 0.],
#     [1., 1.]
# ])
# y = torch.tensor([0, 1, 1, 0])

print(x.shape, y.shape)

torch.Size([4, 2]) torch.Size([4])


보시다시피 shape이나 생성 과정은 OR과 똑같습니다. 다른 것은 $y$에서의 labeling입니다. OR과 다르게 $x = (1, 1)$에 대해서는 0을 labeling했습니다.
이러한 사소한 차이에 대해서도 linear regression model이 잘 학습할 수 있을지 살펴보겠습니다.

## NOTE
여러번 돌려보면서 w,b 가  수렴하는 것을 볼 수 있음

그런데 그것과 별개로 loss가 0.25로 수렴하는 것도 확인 할 수 있는데
왜 그렇게 되는지 의문임

In [162]:
n_epochs = 100
lr = 0.1

w, b = train(n_epochs, lr, w, b, x, y)
print(w, b)

Epoch   0 | Loss: 0.06256163865327835
Epoch   1 | Loss: 0.06255756318569183
Epoch   2 | Loss: 0.06255373358726501
Epoch   3 | Loss: 0.06255017220973969
Epoch   4 | Loss: 0.06254684925079346
Epoch   5 | Loss: 0.06254371255636215
Epoch   6 | Loss: 0.06254082173109055
Epoch   7 | Loss: 0.06253809481859207
Epoch   8 | Loss: 0.06253557652235031
Epoch   9 | Loss: 0.06253322213888168
Epoch  10 | Loss: 0.0625310093164444
Epoch  11 | Loss: 0.06252896040678024
Epoch  12 | Loss: 0.06252701580524445
Epoch  13 | Loss: 0.06252523511648178
Epoch  14 | Loss: 0.06252355873584747
Epoch  15 | Loss: 0.06252199411392212
Epoch  16 | Loss: 0.06252053380012512
Epoch  17 | Loss: 0.06251917779445648
Epoch  18 | Loss: 0.06251788884401321
Epoch  19 | Loss: 0.0625167042016983
Epoch  20 | Loss: 0.06251560896635056
Epoch  21 | Loss: 0.06251457333564758
Epoch  22 | Loss: 0.06251358985900879
Epoch  23 | Loss: 0.06251268833875656
Epoch  24 | Loss: 0.0625118687748909
Epoch  25 | Loss: 0.06251107156276703
Epoch  26 | Los

이전과는 다르게 loss가 1.0보다 작아지지 않는 것을 알 수 있습니다. 실제 예측 결과를 살펴보면 다음과 같습니다.

In [163]:
print(pred(w, b, x))
print(y)

tensor([[0.2496, 0.7499, 0.7499, 1.2503]])
tensor([0, 1, 1, 1])


보시다시피 0과 1에 해당하는 data들을 잘 구분하지 못하는 모습니다. Linear regression model은 XOR을 잘 처리하지 못하는 것을 우리는 이번 실습을 통해 알 수 있습니다.